server:
  port: 8080

spring:
  application:
    name: gitlab-scanner

  datasource:
    url: jdbc:mysql://localhost:3306/gitlab_scanner?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

gitlab:
  api:
    base-url: https://gitlab.com/api/v4